spring.application.name=nails
server.port=7000

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost/nails?serverTimezone=America/Lima&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=raticate2024
server.servlet.context-path=/nails
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=debug